### ISSUE TITLE
Capitalizing the first letter of label

### ISSUE THREAD

**Issue by anwesha2002** [Recode-Hive/Support#104]
![Screenshot 2024-05-30 225819](https://github.com/Recode-Hive/Support/assets/116761608/1a52d55c-b81a-4562-993d-839b72bad070)
In this the labels first letter should be capitalized I would like to do that 
@sanjay-kv I am a gssoc'24 contributor please assign this to me under L3

**Comment by sanjay-kv** [comment]
Actually it should be small letter. as it related to workflow, cant change it.
