### ISSUE TITLE
Please invite me to the Recode-Hive GitHub Community Organization

### ISSUE THREAD

**Issue by shivaniraochepuri21** [Recode-Hive/Support#105]
### Name

Shivani Rao Chepuri

### Discord Username (if applicable)

shivaniraochepuri21

### Additional Context

Trying to dive deep into open source, and learn end to end fundamentals of building a project/application/service. I am into ML, NLP and CV but very interested in learning software fundamentals and engineering. Want to explore the community and statistics of development happening over time. Requesting this invite as a contributor from GSSoC 2024. Thanks IA

**Comment by sanjay-kv** [comment]
<b>Invitation sent to join the GitHub Organisation. Welcome to the community 🎉</b><br><br>
Don't forget after accepting to make it public so it appears on your GitHub profile for everyone else to see. You can do this by finding your name in the GitHub organisation list and change the dropdown to public https://github.com/orgs/Recode-Hive/people<br><br>
